name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Install Frontend dependencies
        run: npm ci
        working-directory: ./app

      - name: Start Frontend server
        run: npm start &
        working-directory: ./app

      - name: Wait for frontend server to start
        run: |
          timeout 30 bash -c "until curl --silent --fail http://localhost:3000; do printf '.'; sleep 1; done"

      - name: Install Backend dependencies
        run: npm install
        working-directory: ./Backend

      - name: Start Backend server
        run: node server.js &
        working-directory: ./Backend
        if: ${{ success() }}

      - name: Wait for backend server to start
        run: sleep 5
        if: ${{ success() }}

      - name: Run automated tests
        run: node test.js
        working-directory: ./Backend
        if: ${{ success() }}
