name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - name: Change to app directory
        run: cd app
        working-directory: ./app
      - name: Install dependencies
        run: npm install
        working-directory: ./app
      - name: Start server
        run: npm start &
        working-directory: ./app
      - name: Wait for server to start
        run: |
          timeout 30 bash -c "until curl --silent --fail http://localhost:3000; do printf '.'; sleep 1; done"
